### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by dhsathiya** [rtCamp/Frappe-Manager#42]
1. [x] CLI command examples in Wiki and map the Wiki link to README.
2. [x] Add rtCamp banner in the README.

Write Wiki for architecture:
1. [x] Directory path
2. [x] Services
5. [x] Default frappe version

Write Wiki `How to?` section for:
1. [x] Create a custom app
2. [x] Where to check logs
4. [x] How to run bench commands
6. [x] How to restart and logic
7. [x] VSCode related commands
 

```[tasklist]
### Tasks
```
